# Generated by Django 3.2.9 on 2021-11-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='patient',
            new_name='patient_name',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.CharField(choices=[('Dr. Martin', 'Dr. Martin'), ('Dr. Mutembei', 'Dr. Mutembei'), ('Dr. Steve', 'Dr. Steve'), ('Dr. Ther', 'Dr. Ther'), ('Dr. Oreste', 'Dr. Oreste')], default='Dr. Oreste', max_length=20),
        ),
    ]
