# Generated by Django 3.2.9 on 2021-11-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='gender',
        ),
        migrations.AddField(
            model_name='appointment',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Rather not say', 'Rather not say')], default='Rather not say', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time_of_day',
            field=models.CharField(choices=[('Morning', '11 AM'), ('Noon', '12 PM'), ('Afternoon', '2 PM'), ('Evening', '4 PM')], default='Noon', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.CharField(choices=[('Dr. Martin', 'Dr. Martin'), ('Dr. Mutembei', 'Dr. Mutembei'), ('Dr. Steve', 'Dr. Steve'), ('Dr. Ther', 'Dr. Ther'), ('Dr. Oreste', 'Dr. Oreste')], default='Dr. Oreste', max_length=20),
        ),
    ]
