# Generated by Django 3.2.9 on 2021-11-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20211113_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Rather Not Say', 'Rather Not Say')], default='Rather Not Say', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_of_day',
            field=models.CharField(choices=[('Morning', '11 AM'), ('Noon', '12 PM'), ('Afternoon', '2 PM'), ('Evening', '4 PM'), ('Night', '8 PM')], default='Noon', max_length=20),
        ),
    ]
