# Generated by Django 3.2.9 on 2021-11-10 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20211108_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='patient_name',
            new_name='patient',
        ),
    ]
