# Generated by Django 3.2.9 on 2021-11-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_rename_patient_name_appointment_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.CharField(choices=[('Morning', '11 AM'), ('Noon', '12 PM'), ('Afternoon', '2 PM'), ('Evening', '4 PM')], default='Noon', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Rather not say', 'Rather not say')], default='Rather not say', max_length=20),
        ),
    ]
